# IO functions for scRNA-seq data
#' @importFrom utils read.table
NULL

read_solo_sparse <- function(cells, regions, mtx) {
  mtx <- Matrix::readMM(mtx)
  regions <- read.table(regions, sep = "\t", header = F)
  cells <- read.table(cells, sep = "\t", header = F)
  rownames(mtx)<- regions$V1
  colnames(mtx)<- cells$V1
  return(mtx)
}

#' Read output from STARsolo
#' @param path Directory contains sample dirs. Sample dirs containing data files.
#' @param assay Load raw or filtered matrix generated by STARsolo. Default: "filtered"
#' @return A single sparse matrix
#' @export
ReadSolo <- function(path, assay="filtered") {
  gsms <- list.dirs(path, recursive = F, full.names = F)
  mm.list <- pbapply::pblapply(gsms, function(gsmID) {
    data.files <- list.files(file.path(path, gsmID, assay))
    cells <- data.files[grepl("^barcodes", data.files)]
    features <- data.files[grepl("^features", data.files)]
    mtx <- data.files[grepl("^matrix", data.files)]
    cells = paste(path, gsmID, assay, cells, sep = "/")
    features = paste(path, gsmID, assay, features, sep = "/")
    mtx = paste(path, gsmID, assay, mtx, sep = "/")
    mm <- read_solo_sparse(cells = cells, regions = features, mtx = mtx)
    colnames(mm) <- paste(gsmID, colnames(mm), sep="_")
    mm
  })
  mm <- do.call(cbind, mm.list)
  return(mm)
}
